
package com.thed.service.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-05-01T14:59:10.222+05:30
 * Generated source version: 3.0.1
 */

@WebFault(name = "exception", targetNamespace = "http://soap.service.thed.com/")
public class ZephyrServiceException extends java.lang.Exception {
    
    private com.thed.service.soap.Exception exception;

    public ZephyrServiceException() {
        super();
    }
    
    public ZephyrServiceException(String message) {
        super(message);
    }
    
    public ZephyrServiceException(String message, Throwable cause) {
        super(message, cause);
    }

    public ZephyrServiceException(String message, com.thed.service.soap.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public ZephyrServiceException(String message, com.thed.service.soap.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.thed.service.soap.Exception getFaultInfo() {
        return this.exception;
    }
}
