
package com.thed.service.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-05-01T14:59:09.789+05:30
 * Generated source version: 3.0.1
 * 
 */
public final class ZephyrSoapService_ZephyrSoapServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://soap.service.thed.com/", "ZephyrSoapService");

    private ZephyrSoapService_ZephyrSoapServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ZephyrSoapService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ZephyrSoapService_Service ss = new ZephyrSoapService_Service(wsdlURL, SERVICE_NAME);
        ZephyrSoapService port = ss.getZephyrSoapServiceImplPort();
        String token = port.login("test.manager", "test.manager");
        
        RemoteProject projectById = port.getProjectById(1L, token);
        
        System.out.println(projectById.toString());
        createTest(port, token);
        {
        System.out.println("Invoking getTestcaseTreeById...");
        java.lang.Long _getTestcaseTreeById_remoteRepositoryId = Long.valueOf(5854157427583884649l);
        java.lang.String _getTestcaseTreeById_token = token;
        try {
            com.thed.service.soap.RemoteRepositoryTree _getTestcaseTreeById__return = port.getTestcaseTreeById(_getTestcaseTreeById_remoteRepositoryId, _getTestcaseTreeById_token);
            System.out.println("getTestcaseTreeById.result=" + _getTestcaseTreeById__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateTestStatus...");
        java.util.List<com.thed.service.soap.RemoteTestResult> _updateTestStatus_testResults = new java.util.ArrayList<com.thed.service.soap.RemoteTestResult>();
        com.thed.service.soap.RemoteTestResult _updateTestStatus_testResultsVal1 = new com.thed.service.soap.RemoteTestResult();
        _updateTestStatus_testResultsVal1.setActualTime(Integer.valueOf(2114051177));
        _updateTestStatus_testResultsVal1.setExecutionDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.052+05:30"));
        _updateTestStatus_testResultsVal1.setExecutionNotes("ExecutionNotes-700493030");
        _updateTestStatus_testResultsVal1.setExecutionStatus("ExecutionStatus-35937386");
        _updateTestStatus_testResultsVal1.setId(Long.valueOf(2212974126044767916l));
        _updateTestStatus_testResultsVal1.setReleaseTestScheduleId("ReleaseTestScheduleId2050561066");
        java.util.List<com.thed.service.soap.RemoteFieldValue> _updateTestStatus_testResultsVal1TestStepExecutions = new java.util.ArrayList<com.thed.service.soap.RemoteFieldValue>();
        com.thed.service.soap.RemoteFieldValue _updateTestStatus_testResultsVal1TestStepExecutionsVal1 = new com.thed.service.soap.RemoteFieldValue();
        _updateTestStatus_testResultsVal1TestStepExecutionsVal1.setKey("Key-32574789");
        java.lang.Object _updateTestStatus_testResultsVal1TestStepExecutionsVal1Value = null;
        _updateTestStatus_testResultsVal1TestStepExecutionsVal1.setValue(_updateTestStatus_testResultsVal1TestStepExecutionsVal1Value);
        _updateTestStatus_testResultsVal1TestStepExecutions.add(_updateTestStatus_testResultsVal1TestStepExecutionsVal1);
        _updateTestStatus_testResultsVal1.getTestStepExecutions().addAll(_updateTestStatus_testResultsVal1TestStepExecutions);
        _updateTestStatus_testResultsVal1.setTesterId(Long.valueOf(2631659663012720518l));
        _updateTestStatus_testResults.add(_updateTestStatus_testResultsVal1);
        java.lang.String _updateTestStatus_token = "_updateTestStatus_token-1096926522";
        try {
            java.util.List<com.thed.service.soap.RemoteFieldValue> _updateTestStatus__return = port.updateTestStatus(_updateTestStatus_testResults, _updateTestStatus_token);
            System.out.println("updateTestStatus.result=" + _updateTestStatus__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateRequirement...");
        java.lang.Long _updateRequirement_remoteRequirementId = Long.valueOf(-4567153165353365497l);
        java.util.List<com.thed.service.soap.RemoteFieldValue> _updateRequirement_remoteFieldValues = new java.util.ArrayList<com.thed.service.soap.RemoteFieldValue>();
        com.thed.service.soap.RemoteFieldValue _updateRequirement_remoteFieldValuesVal1 = new com.thed.service.soap.RemoteFieldValue();
        _updateRequirement_remoteFieldValuesVal1.setKey("Key-875870963");
        java.lang.Object _updateRequirement_remoteFieldValuesVal1Value = null;
        _updateRequirement_remoteFieldValuesVal1.setValue(_updateRequirement_remoteFieldValuesVal1Value);
        _updateRequirement_remoteFieldValues.add(_updateRequirement_remoteFieldValuesVal1);
        java.lang.String _updateRequirement_token = "_updateRequirement_token-94621429";
        try {
            java.lang.Long _updateRequirement__return = port.updateRequirement(_updateRequirement_remoteRequirementId, _updateRequirement_remoteFieldValues, _updateRequirement_token);
            System.out.println("updateRequirement.result=" + _updateRequirement__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTestCaseTreesByCriteria...");
        java.util.List<com.thed.service.soap.RemoteCriteria> _getTestCaseTreesByCriteria_searchCriterias = new java.util.ArrayList<com.thed.service.soap.RemoteCriteria>();
        com.thed.service.soap.RemoteCriteria _getTestCaseTreesByCriteria_searchCriteriasVal1 = new com.thed.service.soap.RemoteCriteria();
        _getTestCaseTreesByCriteria_searchCriteriasVal1.setSearchName("SearchName-1351598864");
        com.thed.service.soap.SearchOperation _getTestCaseTreesByCriteria_searchCriteriasVal1SearchOperation = com.thed.service.soap.SearchOperation.GREATER_THAN;
        _getTestCaseTreesByCriteria_searchCriteriasVal1.setSearchOperation(_getTestCaseTreesByCriteria_searchCriteriasVal1SearchOperation);
        _getTestCaseTreesByCriteria_searchCriteriasVal1.setSearchValue("SearchValue314979344");
        _getTestCaseTreesByCriteria_searchCriterias.add(_getTestCaseTreesByCriteria_searchCriteriasVal1);
        java.lang.Boolean _getTestCaseTreesByCriteria_returnAllDataFlag = Boolean.valueOf(false);
        java.lang.String _getTestCaseTreesByCriteria_token = "_getTestCaseTreesByCriteria_token79800945";
        try {
            java.util.List<com.thed.service.soap.RemoteRepositoryTree> _getTestCaseTreesByCriteria__return = port.getTestCaseTreesByCriteria(_getTestCaseTreesByCriteria_searchCriterias, _getTestCaseTreesByCriteria_returnAllDataFlag, _getTestCaseTreesByCriteria_token);
            System.out.println("getTestCaseTreesByCriteria.result=" + _getTestCaseTreesByCriteria__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getRequirementsByCriteria...");
        java.util.List<com.thed.service.soap.RemoteCriteria> _getRequirementsByCriteria_searchCriterias = new java.util.ArrayList<com.thed.service.soap.RemoteCriteria>();
        com.thed.service.soap.RemoteCriteria _getRequirementsByCriteria_searchCriteriasVal1 = new com.thed.service.soap.RemoteCriteria();
        _getRequirementsByCriteria_searchCriteriasVal1.setSearchName("SearchName-657832523");
        com.thed.service.soap.SearchOperation _getRequirementsByCriteria_searchCriteriasVal1SearchOperation = com.thed.service.soap.SearchOperation.GREATER_THAN;
        _getRequirementsByCriteria_searchCriteriasVal1.setSearchOperation(_getRequirementsByCriteria_searchCriteriasVal1SearchOperation);
        _getRequirementsByCriteria_searchCriteriasVal1.setSearchValue("SearchValue-499075457");
        _getRequirementsByCriteria_searchCriterias.add(_getRequirementsByCriteria_searchCriteriasVal1);
        java.lang.Boolean _getRequirementsByCriteria_returnAllDataFlag = Boolean.valueOf(true);
        java.lang.String _getRequirementsByCriteria_token = "_getRequirementsByCriteria_token-368105746";
        try {
            java.util.List<com.thed.service.soap.RemoteRequirement> _getRequirementsByCriteria__return = port.getRequirementsByCriteria(_getRequirementsByCriteria_searchCriterias, _getRequirementsByCriteria_returnAllDataFlag, _getRequirementsByCriteria_token);
            System.out.println("getRequirementsByCriteria.result=" + _getRequirementsByCriteria__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getProjectsByCriteria...");
        java.util.List<com.thed.service.soap.RemoteCriteria> _getProjectsByCriteria_searchCriterias = new java.util.ArrayList<com.thed.service.soap.RemoteCriteria>();
        com.thed.service.soap.RemoteCriteria _getProjectsByCriteria_searchCriteriasVal1 = new com.thed.service.soap.RemoteCriteria();
        _getProjectsByCriteria_searchCriteriasVal1.setSearchName("SearchName1206594768");
        com.thed.service.soap.SearchOperation _getProjectsByCriteria_searchCriteriasVal1SearchOperation = com.thed.service.soap.SearchOperation.BETWEEN;
        _getProjectsByCriteria_searchCriteriasVal1.setSearchOperation(_getProjectsByCriteria_searchCriteriasVal1SearchOperation);
        _getProjectsByCriteria_searchCriteriasVal1.setSearchValue("SearchValue-1744006068");
        _getProjectsByCriteria_searchCriterias.add(_getProjectsByCriteria_searchCriteriasVal1);
        java.lang.Boolean _getProjectsByCriteria_returnAllDataFlag = Boolean.valueOf(true);
        java.lang.String _getProjectsByCriteria_token = "_getProjectsByCriteria_token-298314048";
        try {
            java.util.List<com.thed.service.soap.RemoteProject> _getProjectsByCriteria__return = port.getProjectsByCriteria(_getProjectsByCriteria_searchCriterias, _getProjectsByCriteria_returnAllDataFlag, _getProjectsByCriteria_token);
            System.out.println("getProjectsByCriteria.result=" + _getProjectsByCriteria__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getCustomFields...");
        java.lang.String _getCustomFields_entityName = "_getCustomFields_entityName-296925460";
        java.lang.String _getCustomFields_token = "_getCustomFields_token-866060576";
        try {
            java.util.List<com.thed.service.soap.RemoteCustomField> _getCustomFields__return = port.getCustomFields(_getCustomFields_entityName, _getCustomFields_token);
            System.out.println("getCustomFields.result=" + _getCustomFields__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getRequirementTreesByCriteria...");
        java.util.List<com.thed.service.soap.RemoteCriteria> _getRequirementTreesByCriteria_searchCriterias = new java.util.ArrayList<com.thed.service.soap.RemoteCriteria>();
        com.thed.service.soap.RemoteCriteria _getRequirementTreesByCriteria_searchCriteriasVal1 = new com.thed.service.soap.RemoteCriteria();
        _getRequirementTreesByCriteria_searchCriteriasVal1.setSearchName("SearchName976574895");
        com.thed.service.soap.SearchOperation _getRequirementTreesByCriteria_searchCriteriasVal1SearchOperation = com.thed.service.soap.SearchOperation.IS_NULL;
        _getRequirementTreesByCriteria_searchCriteriasVal1.setSearchOperation(_getRequirementTreesByCriteria_searchCriteriasVal1SearchOperation);
        _getRequirementTreesByCriteria_searchCriteriasVal1.setSearchValue("SearchValue-2026347659");
        _getRequirementTreesByCriteria_searchCriterias.add(_getRequirementTreesByCriteria_searchCriteriasVal1);
        java.lang.Boolean _getRequirementTreesByCriteria_returnAllDataFlag = Boolean.valueOf(false);
        java.lang.String _getRequirementTreesByCriteria_token = "_getRequirementTreesByCriteria_token1689687369";
        try {
            java.util.List<com.thed.service.soap.RemoteRequirementTree> _getRequirementTreesByCriteria__return = port.getRequirementTreesByCriteria(_getRequirementTreesByCriteria_searchCriterias, _getRequirementTreesByCriteria_returnAllDataFlag, _getRequirementTreesByCriteria_token);
            System.out.println("getRequirementTreesByCriteria.result=" + _getRequirementTreesByCriteria__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking addPhaseToCycle...");
        com.thed.service.soap.RemotePhase _addPhaseToCycle_remotePhase = new com.thed.service.soap.RemotePhase();
        _addPhaseToCycle_remotePhase.setId(Long.valueOf(3606166491601284846l));
        com.thed.service.soap.RemoteNameValue _addPhaseToCycle_remotePhaseRemoteRepository = new com.thed.service.soap.RemoteNameValue();
        com.thed.service.soap.RemoteData _addPhaseToCycle_remotePhaseRemoteRepositoryRemoteData = new com.thed.service.soap.RemoteData();
        _addPhaseToCycle_remotePhaseRemoteRepositoryRemoteData.setId(-4817222518846544915l);
        _addPhaseToCycle_remotePhaseRemoteRepositoryRemoteData.setName("Name856389113");
        _addPhaseToCycle_remotePhaseRemoteRepository.setRemoteData(_addPhaseToCycle_remotePhaseRemoteRepositoryRemoteData);
        _addPhaseToCycle_remotePhase.setRemoteRepository(_addPhaseToCycle_remotePhaseRemoteRepository);
        _addPhaseToCycle_remotePhase.setStartDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.100+05:30"));
        _addPhaseToCycle_remotePhase.setEndDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.100+05:30"));
        _addPhaseToCycle_remotePhase.setFreeForm(Boolean.valueOf(false));
        com.thed.service.soap.RemoteNameValue _addPhaseToCycle_remotePhaseRemoteCycle = new com.thed.service.soap.RemoteNameValue();
        com.thed.service.soap.RemoteData _addPhaseToCycle_remotePhaseRemoteCycleRemoteData = new com.thed.service.soap.RemoteData();
        _addPhaseToCycle_remotePhaseRemoteCycleRemoteData.setId(-6722183610684835802l);
        _addPhaseToCycle_remotePhaseRemoteCycleRemoteData.setName("Name-1269435082");
        _addPhaseToCycle_remotePhaseRemoteCycle.setRemoteData(_addPhaseToCycle_remotePhaseRemoteCycleRemoteData);
        _addPhaseToCycle_remotePhase.setRemoteCycle(_addPhaseToCycle_remotePhaseRemoteCycle);
        java.lang.Integer _addPhaseToCycle_bulkAssign = Integer.valueOf(597456851);
        java.lang.String _addPhaseToCycle_token = "_addPhaseToCycle_token843647067";
        try {
            java.lang.Long _addPhaseToCycle__return = port.addPhaseToCycle(_addPhaseToCycle_remotePhase, _addPhaseToCycle_bulkAssign, _addPhaseToCycle_token);
            System.out.println("addPhaseToCycle.result=" + _addPhaseToCycle__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAttachmentsByCriteria...");
        java.util.List<com.thed.service.soap.RemoteCriteria> _getAttachmentsByCriteria_searchCriterias = new java.util.ArrayList<com.thed.service.soap.RemoteCriteria>();
        com.thed.service.soap.RemoteCriteria _getAttachmentsByCriteria_searchCriteriasVal1 = new com.thed.service.soap.RemoteCriteria();
        _getAttachmentsByCriteria_searchCriteriasVal1.setSearchName("SearchName325019942");
        com.thed.service.soap.SearchOperation _getAttachmentsByCriteria_searchCriteriasVal1SearchOperation = com.thed.service.soap.SearchOperation.BETWEEN;
        _getAttachmentsByCriteria_searchCriteriasVal1.setSearchOperation(_getAttachmentsByCriteria_searchCriteriasVal1SearchOperation);
        _getAttachmentsByCriteria_searchCriteriasVal1.setSearchValue("SearchValue-1506504810");
        _getAttachmentsByCriteria_searchCriterias.add(_getAttachmentsByCriteria_searchCriteriasVal1);
        java.lang.Boolean _getAttachmentsByCriteria_returnAllDataFlag = Boolean.valueOf(false);
        java.lang.String _getAttachmentsByCriteria_token = "_getAttachmentsByCriteria_token893767639";
        try {
            java.util.List<com.thed.service.soap.RemoteAttachment> _getAttachmentsByCriteria__return = port.getAttachmentsByCriteria(_getAttachmentsByCriteria_searchCriterias, _getAttachmentsByCriteria_returnAllDataFlag, _getAttachmentsByCriteria_token);
            System.out.println("getAttachmentsByCriteria.result=" + _getAttachmentsByCriteria__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking assignTestSchedules...");
        java.util.List<com.thed.service.soap.RemoteReleaseTestSchedule> _assignTestSchedules_remoteReleaseTestSchedules = new java.util.ArrayList<com.thed.service.soap.RemoteReleaseTestSchedule>();
        com.thed.service.soap.RemoteReleaseTestSchedule _assignTestSchedules_remoteReleaseTestSchedulesVal1 = new com.thed.service.soap.RemoteReleaseTestSchedule();
        _assignTestSchedules_remoteReleaseTestSchedulesVal1.setTestScheduleId(1378659873098451485l);
        _assignTestSchedules_remoteReleaseTestSchedulesVal1.setAssignmentDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.112+05:30"));
        _assignTestSchedules_remoteReleaseTestSchedulesVal1.setEstimatedTime(Long.valueOf(6828950600755503407l));
        _assignTestSchedules_remoteReleaseTestSchedulesVal1.setComment("Comment585650089");
        _assignTestSchedules_remoteReleaseTestSchedulesVal1.setTesterId(Long.valueOf(9216768520207827376l));
        _assignTestSchedules_remoteReleaseTestSchedulesVal1.setRemoteRepositoryTestcaseId(Long.valueOf(7370802454704842408l));
        _assignTestSchedules_remoteReleaseTestSchedulesVal1.setRemoteTestcaseId(Long.valueOf(-2306089280929089343l));
        _assignTestSchedules_remoteReleaseTestSchedulesVal1.setCyclePhaseId(Long.valueOf(-6077098969375927246l));
        com.thed.service.soap.TestResult _assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResult = new com.thed.service.soap.TestResult();
        _assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResult.setAttachmentLocation("AttachmentLocation-1887946572");
        com.thed.service.soap.Defect _assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResultDefect = new com.thed.service.soap.Defect();
        _assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResultDefect.setBugId(-6213220715966187653l);
        _assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResultDefect.setCreatedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.112+05:30"));
        _assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResultDefect.setDescription("Description-1002246253");
        _assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResultDefect.setExternalId("ExternalId-2083174415");
        _assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResultDefect.setId(Long.valueOf(2386897460651132321l));
        _assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResultDefect.setPriority("Priority380549834");
        _assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResultDefect.setSeverity("Severity-1767120452");
        _assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResultDefect.setState("State784436750");
        _assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResultDefect.setStatus("Status1505647879");
        java.util.List<com.thed.service.soap.TestResult> _assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResultDefectTestResults = new java.util.ArrayList<com.thed.service.soap.TestResult>();
        _assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResultDefect.getTestResults().addAll(_assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResultDefectTestResults);
        _assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResult.setDefect(_assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResultDefect);
        _assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResult.setExecutionDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.115+05:30"));
        _assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResult.setExecutionNotes("ExecutionNotes1079832975");
        _assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResult.setExecutionStatus("ExecutionStatus-260163836");
        _assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResult.setId(5115220230910329302l);
        _assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResult.setReleaseTestScheduleId(Long.valueOf(-3591545293632296540l));
        _assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResult.setStatus("Status1037372958");
        _assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResult.setTesterId(Long.valueOf(-3370716087183145707l));
        _assignTestSchedules_remoteReleaseTestSchedulesVal1.setLastTestResult(_assignTestSchedules_remoteReleaseTestSchedulesVal1LastTestResult);
        _assignTestSchedules_remoteReleaseTestSchedulesVal1.setAttachmentCount(Integer.valueOf(1662069648));
        _assignTestSchedules_remoteReleaseTestSchedulesVal1.setScriptName("ScriptName-146221311");
        _assignTestSchedules_remoteReleaseTestSchedulesVal1.setScriptId("ScriptId802671985");
        _assignTestSchedules_remoteReleaseTestSchedulesVal1.setScriptPath("ScriptPath-60701564");
        java.util.List<com.thed.service.soap.RemoteFieldValue> _assignTestSchedules_remoteReleaseTestSchedulesVal1RemoteFieldValues = new java.util.ArrayList<com.thed.service.soap.RemoteFieldValue>();
        com.thed.service.soap.RemoteFieldValue _assignTestSchedules_remoteReleaseTestSchedulesVal1RemoteFieldValuesVal1 = new com.thed.service.soap.RemoteFieldValue();
        _assignTestSchedules_remoteReleaseTestSchedulesVal1RemoteFieldValuesVal1.setKey("Key799694154");
        java.lang.Object _assignTestSchedules_remoteReleaseTestSchedulesVal1RemoteFieldValuesVal1Value = null;
        _assignTestSchedules_remoteReleaseTestSchedulesVal1RemoteFieldValuesVal1.setValue(_assignTestSchedules_remoteReleaseTestSchedulesVal1RemoteFieldValuesVal1Value);
        _assignTestSchedules_remoteReleaseTestSchedulesVal1RemoteFieldValues.add(_assignTestSchedules_remoteReleaseTestSchedulesVal1RemoteFieldValuesVal1);
        _assignTestSchedules_remoteReleaseTestSchedulesVal1.getRemoteFieldValues().addAll(_assignTestSchedules_remoteReleaseTestSchedulesVal1RemoteFieldValues);
        _assignTestSchedules_remoteReleaseTestSchedulesVal1.setActualTime(Integer.valueOf(-937023860));
        java.util.List<com.thed.service.soap.RemoteDefect> _assignTestSchedules_remoteReleaseTestSchedulesVal1Defects = new java.util.ArrayList<com.thed.service.soap.RemoteDefect>();
        com.thed.service.soap.RemoteDefect _assignTestSchedules_remoteReleaseTestSchedulesVal1DefectsVal1 = new com.thed.service.soap.RemoteDefect();
        _assignTestSchedules_remoteReleaseTestSchedulesVal1DefectsVal1.setDefectId(Long.valueOf(7736959723702299811l));
        _assignTestSchedules_remoteReleaseTestSchedulesVal1DefectsVal1.setDescription("Description2123603865");
        _assignTestSchedules_remoteReleaseTestSchedulesVal1DefectsVal1.setCreatedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.121+05:30"));
        _assignTestSchedules_remoteReleaseTestSchedulesVal1DefectsVal1.setDefectStatus("DefectStatus-472504557");
        _assignTestSchedules_remoteReleaseTestSchedulesVal1DefectsVal1.setPriority("Priority-972851351");
        _assignTestSchedules_remoteReleaseTestSchedulesVal1DefectsVal1.setSeverity("Severity-1106652223");
        _assignTestSchedules_remoteReleaseTestSchedulesVal1Defects.add(_assignTestSchedules_remoteReleaseTestSchedulesVal1DefectsVal1);
        _assignTestSchedules_remoteReleaseTestSchedulesVal1.getDefects().addAll(_assignTestSchedules_remoteReleaseTestSchedulesVal1Defects);
        _assignTestSchedules_remoteReleaseTestSchedules.add(_assignTestSchedules_remoteReleaseTestSchedulesVal1);
        java.lang.String _assignTestSchedules_token = "_assignTestSchedules_token937266301";
        try {
            java.util.List<com.thed.service.soap.RemoteFieldValue> _assignTestSchedules__return = port.assignTestSchedules(_assignTestSchedules_remoteReleaseTestSchedules, _assignTestSchedules_token);
            System.out.println("assignTestSchedules.result=" + _assignTestSchedules__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createNewTestcaseTree...");
        com.thed.service.soap.RemoteRepositoryTree _createNewTestcaseTree_remoteRepositoryTree = new com.thed.service.soap.RemoteRepositoryTree();
        _createNewTestcaseTree_remoteRepositoryTree.setId(Long.valueOf(-614315920220541763l));
        _createNewTestcaseTree_remoteRepositoryTree.setType("Type853217594");
        _createNewTestcaseTree_remoteRepositoryTree.setName("Name1842973533");
        _createNewTestcaseTree_remoteRepositoryTree.setDescription("Description-2034911585");
        com.thed.service.soap.RemoteRepositoryTree _createNewTestcaseTree_remoteRepositoryTreeParent = new com.thed.service.soap.RemoteRepositoryTree();
        _createNewTestcaseTree_remoteRepositoryTreeParent.setId(Long.valueOf(-5409005630072154560l));
        _createNewTestcaseTree_remoteRepositoryTreeParent.setType("Type-158305150");
        _createNewTestcaseTree_remoteRepositoryTreeParent.setName("Name553836858");
        _createNewTestcaseTree_remoteRepositoryTreeParent.setDescription("Description-378074736");
        com.thed.service.soap.RemoteRepositoryTree _createNewTestcaseTree_remoteRepositoryTreeParentParent = new com.thed.service.soap.RemoteRepositoryTree();
        _createNewTestcaseTree_remoteRepositoryTreeParentParent.setId(Long.valueOf(-1284705817295358008l));
        _createNewTestcaseTree_remoteRepositoryTreeParentParent.setType("Type425441025");
        _createNewTestcaseTree_remoteRepositoryTreeParentParent.setName("Name507572596");
        _createNewTestcaseTree_remoteRepositoryTreeParentParent.setDescription("Description-1685565638");
        com.thed.service.soap.RemoteRepositoryTree _createNewTestcaseTree_remoteRepositoryTreeParentParentParent = new com.thed.service.soap.RemoteRepositoryTree();
        _createNewTestcaseTree_remoteRepositoryTreeParentParentParent.setId(Long.valueOf(8635716684023822926l));
        _createNewTestcaseTree_remoteRepositoryTreeParentParentParent.setType("Type192365780");
        _createNewTestcaseTree_remoteRepositoryTreeParentParentParent.setName("Name-1803366118");
        _createNewTestcaseTree_remoteRepositoryTreeParentParentParent.setDescription("Description1762418942");
                _createNewTestcaseTree_remoteRepositoryTreeParentParentParent.setParent(null);
        java.util.List<com.thed.service.soap.RemoteRepositoryChild> _createNewTestcaseTree_remoteRepositoryTreeParentParentParentCategories = new java.util.ArrayList<com.thed.service.soap.RemoteRepositoryChild>();
        _createNewTestcaseTree_remoteRepositoryTreeParentParentParent.getCategories().addAll(_createNewTestcaseTree_remoteRepositoryTreeParentParentParentCategories);
        java.util.List<com.thed.service.soap.RemoteNameValue> _createNewTestcaseTree_remoteRepositoryTreeParentParentParentRemoteRepositoryUser = new java.util.ArrayList<com.thed.service.soap.RemoteNameValue>();
        _createNewTestcaseTree_remoteRepositoryTreeParentParentParent.getRemoteRepositoryUser().addAll(_createNewTestcaseTree_remoteRepositoryTreeParentParentParentRemoteRepositoryUser);
        _createNewTestcaseTree_remoteRepositoryTreeParentParentParent.setReleaseId(Long.valueOf(5354813718428844571l));
        _createNewTestcaseTree_remoteRepositoryTreeParentParentParent.setLinkedTCRCatalogTreeId(Long.valueOf(-5372365923990899111l));
        _createNewTestcaseTree_remoteRepositoryTreeParentParent.setParent(_createNewTestcaseTree_remoteRepositoryTreeParentParentParent);
        java.util.List<com.thed.service.soap.RemoteRepositoryChild> _createNewTestcaseTree_remoteRepositoryTreeParentParentCategories = new java.util.ArrayList<com.thed.service.soap.RemoteRepositoryChild>();
        _createNewTestcaseTree_remoteRepositoryTreeParentParent.getCategories().addAll(_createNewTestcaseTree_remoteRepositoryTreeParentParentCategories);
        java.util.List<com.thed.service.soap.RemoteNameValue> _createNewTestcaseTree_remoteRepositoryTreeParentParentRemoteRepositoryUser = new java.util.ArrayList<com.thed.service.soap.RemoteNameValue>();
        _createNewTestcaseTree_remoteRepositoryTreeParentParent.getRemoteRepositoryUser().addAll(_createNewTestcaseTree_remoteRepositoryTreeParentParentRemoteRepositoryUser);
        _createNewTestcaseTree_remoteRepositoryTreeParentParent.setReleaseId(Long.valueOf(-2669233351305112939l));
        _createNewTestcaseTree_remoteRepositoryTreeParentParent.setLinkedTCRCatalogTreeId(Long.valueOf(-2539397450004076331l));
        _createNewTestcaseTree_remoteRepositoryTreeParent.setParent(_createNewTestcaseTree_remoteRepositoryTreeParentParent);
        java.util.List<com.thed.service.soap.RemoteRepositoryChild> _createNewTestcaseTree_remoteRepositoryTreeParentCategories = new java.util.ArrayList<com.thed.service.soap.RemoteRepositoryChild>();
        com.thed.service.soap.RemoteRepositoryChild _createNewTestcaseTree_remoteRepositoryTreeParentCategoriesVal1 = new com.thed.service.soap.RemoteRepositoryChild();
        _createNewTestcaseTree_remoteRepositoryTreeParentCategoriesVal1.setId(Long.valueOf(93636461781503813l));
        _createNewTestcaseTree_remoteRepositoryTreeParentCategoriesVal1.setName("Name-989513525");
        _createNewTestcaseTree_remoteRepositoryTreeParentCategories.add(_createNewTestcaseTree_remoteRepositoryTreeParentCategoriesVal1);
        _createNewTestcaseTree_remoteRepositoryTreeParent.getCategories().addAll(_createNewTestcaseTree_remoteRepositoryTreeParentCategories);
        java.util.List<com.thed.service.soap.RemoteNameValue> _createNewTestcaseTree_remoteRepositoryTreeParentRemoteRepositoryUser = new java.util.ArrayList<com.thed.service.soap.RemoteNameValue>();
        com.thed.service.soap.RemoteNameValue _createNewTestcaseTree_remoteRepositoryTreeParentRemoteRepositoryUserVal1 = new com.thed.service.soap.RemoteNameValue();
        com.thed.service.soap.RemoteData _createNewTestcaseTree_remoteRepositoryTreeParentRemoteRepositoryUserVal1RemoteData = new com.thed.service.soap.RemoteData();
        _createNewTestcaseTree_remoteRepositoryTreeParentRemoteRepositoryUserVal1RemoteData.setId(1129572794167658928l);
        _createNewTestcaseTree_remoteRepositoryTreeParentRemoteRepositoryUserVal1RemoteData.setName("Name580763382");
        _createNewTestcaseTree_remoteRepositoryTreeParentRemoteRepositoryUserVal1.setRemoteData(_createNewTestcaseTree_remoteRepositoryTreeParentRemoteRepositoryUserVal1RemoteData);
        _createNewTestcaseTree_remoteRepositoryTreeParentRemoteRepositoryUser.add(_createNewTestcaseTree_remoteRepositoryTreeParentRemoteRepositoryUserVal1);
        _createNewTestcaseTree_remoteRepositoryTreeParent.getRemoteRepositoryUser().addAll(_createNewTestcaseTree_remoteRepositoryTreeParentRemoteRepositoryUser);
        _createNewTestcaseTree_remoteRepositoryTreeParent.setReleaseId(Long.valueOf(3379804246109935960l));
        _createNewTestcaseTree_remoteRepositoryTreeParent.setLinkedTCRCatalogTreeId(Long.valueOf(-2600148449525390961l));
        _createNewTestcaseTree_remoteRepositoryTree.setParent(_createNewTestcaseTree_remoteRepositoryTreeParent);
        java.util.List<com.thed.service.soap.RemoteRepositoryChild> _createNewTestcaseTree_remoteRepositoryTreeCategories = new java.util.ArrayList<com.thed.service.soap.RemoteRepositoryChild>();
        com.thed.service.soap.RemoteRepositoryChild _createNewTestcaseTree_remoteRepositoryTreeCategoriesVal1 = new com.thed.service.soap.RemoteRepositoryChild();
        _createNewTestcaseTree_remoteRepositoryTreeCategoriesVal1.setId(Long.valueOf(-7958242463626274555l));
        _createNewTestcaseTree_remoteRepositoryTreeCategoriesVal1.setName("Name-300587862");
        _createNewTestcaseTree_remoteRepositoryTreeCategories.add(_createNewTestcaseTree_remoteRepositoryTreeCategoriesVal1);
        _createNewTestcaseTree_remoteRepositoryTree.getCategories().addAll(_createNewTestcaseTree_remoteRepositoryTreeCategories);
        java.util.List<com.thed.service.soap.RemoteNameValue> _createNewTestcaseTree_remoteRepositoryTreeRemoteRepositoryUser = new java.util.ArrayList<com.thed.service.soap.RemoteNameValue>();
        com.thed.service.soap.RemoteNameValue _createNewTestcaseTree_remoteRepositoryTreeRemoteRepositoryUserVal1 = new com.thed.service.soap.RemoteNameValue();
        com.thed.service.soap.RemoteData _createNewTestcaseTree_remoteRepositoryTreeRemoteRepositoryUserVal1RemoteData = new com.thed.service.soap.RemoteData();
        _createNewTestcaseTree_remoteRepositoryTreeRemoteRepositoryUserVal1RemoteData.setId(6463682147765986797l);
        _createNewTestcaseTree_remoteRepositoryTreeRemoteRepositoryUserVal1RemoteData.setName("Name1037170501");
        _createNewTestcaseTree_remoteRepositoryTreeRemoteRepositoryUserVal1.setRemoteData(_createNewTestcaseTree_remoteRepositoryTreeRemoteRepositoryUserVal1RemoteData);
        _createNewTestcaseTree_remoteRepositoryTreeRemoteRepositoryUser.add(_createNewTestcaseTree_remoteRepositoryTreeRemoteRepositoryUserVal1);
        _createNewTestcaseTree_remoteRepositoryTree.getRemoteRepositoryUser().addAll(_createNewTestcaseTree_remoteRepositoryTreeRemoteRepositoryUser);
        _createNewTestcaseTree_remoteRepositoryTree.setReleaseId(Long.valueOf(8016664948483595625l));
        _createNewTestcaseTree_remoteRepositoryTree.setLinkedTCRCatalogTreeId(Long.valueOf(2547373265101400582l));
        java.lang.String _createNewTestcaseTree_token = "_createNewTestcaseTree_token-607877948";
        try {
            java.lang.Long _createNewTestcaseTree__return = port.createNewTestcaseTree(_createNewTestcaseTree_remoteRepositoryTree, _createNewTestcaseTree_token);
            System.out.println("createNewTestcaseTree.result=" + _createNewTestcaseTree__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTestcaseById...");
        java.lang.Long _getTestcaseById_testcaseId = Long.valueOf(3934812913952639407l);
        java.lang.String _getTestcaseById_token = "_getTestcaseById_token822682768";
        try {
            com.thed.service.soap.RemoteRepositoryTreeTestcase _getTestcaseById__return = port.getTestcaseById(_getTestcaseById_testcaseId, _getTestcaseById_token);
            System.out.println("getTestcaseById.result=" + _getTestcaseById__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteAttachmentsByCriteria...");
        java.lang.String _deleteAttachmentsByCriteria_entityName = "_deleteAttachmentsByCriteria_entityName-988227447";
        java.lang.Long _deleteAttachmentsByCriteria_entityId = Long.valueOf(6391990598519509343l);
        java.lang.String _deleteAttachmentsByCriteria_token = "_deleteAttachmentsByCriteria_token1010764282";
        try {
            java.util.List<com.thed.service.soap.RemoteFieldValue> _deleteAttachmentsByCriteria__return = port.deleteAttachmentsByCriteria(_deleteAttachmentsByCriteria_entityName, _deleteAttachmentsByCriteria_entityId, _deleteAttachmentsByCriteria_token);
            System.out.println("deleteAttachmentsByCriteria.result=" + _deleteAttachmentsByCriteria__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateTestcase...");
        java.lang.Long _updateTestcase_testCaseId = Long.valueOf(-3147214811521196336l);
        java.util.List<com.thed.service.soap.RemoteFieldValue> _updateTestcase_remoteFieldValues = new java.util.ArrayList<com.thed.service.soap.RemoteFieldValue>();
        com.thed.service.soap.RemoteFieldValue _updateTestcase_remoteFieldValuesVal1 = new com.thed.service.soap.RemoteFieldValue();
        _updateTestcase_remoteFieldValuesVal1.setKey("Key1950841330");
        java.lang.Object _updateTestcase_remoteFieldValuesVal1Value = null;
        _updateTestcase_remoteFieldValuesVal1.setValue(_updateTestcase_remoteFieldValuesVal1Value);
        _updateTestcase_remoteFieldValues.add(_updateTestcase_remoteFieldValuesVal1);
        java.lang.String _updateTestcase_token = "_updateTestcase_token909628126";
        try {
            java.lang.Long _updateTestcase__return = port.updateTestcase(_updateTestcase_testCaseId, _updateTestcase_remoteFieldValues, _updateTestcase_token);
            System.out.println("updateTestcase.result=" + _updateTestcase__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTestSchedulesByCriteria...");
        java.util.List<com.thed.service.soap.RemoteCriteria> _getTestSchedulesByCriteria_searchCriterias = new java.util.ArrayList<com.thed.service.soap.RemoteCriteria>();
        com.thed.service.soap.RemoteCriteria _getTestSchedulesByCriteria_searchCriteriasVal1 = new com.thed.service.soap.RemoteCriteria();
        _getTestSchedulesByCriteria_searchCriteriasVal1.setSearchName("SearchName-40612565");
        com.thed.service.soap.SearchOperation _getTestSchedulesByCriteria_searchCriteriasVal1SearchOperation = com.thed.service.soap.SearchOperation.LIKE;
        _getTestSchedulesByCriteria_searchCriteriasVal1.setSearchOperation(_getTestSchedulesByCriteria_searchCriteriasVal1SearchOperation);
        _getTestSchedulesByCriteria_searchCriteriasVal1.setSearchValue("SearchValue-1528692070");
        _getTestSchedulesByCriteria_searchCriterias.add(_getTestSchedulesByCriteria_searchCriteriasVal1);
        java.lang.Boolean _getTestSchedulesByCriteria_returnAllDataFlag = Boolean.valueOf(true);
        java.lang.String _getTestSchedulesByCriteria_token = "_getTestSchedulesByCriteria_token-531853955";
        try {
            java.util.List<com.thed.service.soap.RemoteReleaseTestSchedule> _getTestSchedulesByCriteria__return = port.getTestSchedulesByCriteria(_getTestSchedulesByCriteria_searchCriterias, _getTestSchedulesByCriteria_returnAllDataFlag, _getTestSchedulesByCriteria_token);
            System.out.println("getTestSchedulesByCriteria.result=" + _getTestSchedulesByCriteria__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking login...");
        java.lang.String _login_username = "_login_username2043890702";
        java.lang.String _login_password = "_login_password1534268887";
        try {
            java.lang.String _login__return = port.login(_login_username, _login_password);
            System.out.println("login.result=" + _login__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createNewTestcase...");
        com.thed.service.soap.RemoteRepositoryTreeTestcase _createNewTestcase_remoteRepositoryTreeTestcase = new com.thed.service.soap.RemoteRepositoryTreeTestcase();
        _createNewTestcase_remoteRepositoryTreeTestcase.setId(Long.valueOf(7303930448255555593l));
        _createNewTestcase_remoteRepositoryTreeTestcase.setRemoteRepositoryId(Long.valueOf(3452344024328914496l));
        com.thed.service.soap.RemoteTestcase _createNewTestcase_remoteRepositoryTreeTestcaseTestcase = new com.thed.service.soap.RemoteTestcase();
        com.thed.service.soap.RemoteCustomizableEntity.CustomProperties _createNewTestcase_remoteRepositoryTreeTestcaseTestcaseCustomProperties = new com.thed.service.soap.RemoteCustomizableEntity.CustomProperties();
        java.util.List<com.thed.service.soap.RemoteCustomizableEntity.CustomProperties.Entry> _createNewTestcase_remoteRepositoryTreeTestcaseTestcaseCustomPropertiesEntry = new java.util.ArrayList<com.thed.service.soap.RemoteCustomizableEntity.CustomProperties.Entry>();
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcaseCustomProperties.getEntry().addAll(_createNewTestcase_remoteRepositoryTreeTestcaseTestcaseCustomPropertiesEntry);
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcase.setCustomProperties(_createNewTestcase_remoteRepositoryTreeTestcaseTestcaseCustomProperties);
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcase.setId(Long.valueOf(8670482535361275367l));
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcase.setName("Name940689728");
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcase.setDescription("Description310088579");
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcase.setPriority("Priority703407780");
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcase.setTag("Tag1798676893");
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcase.setLastModifiedOn(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.150+05:30"));
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcase.setCreationDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.153+05:30"));
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcase.setComments("Comments-1302773989");
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcase.setEstimatedTime(Integer.valueOf(-838386775));
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcase.setUserId(Long.valueOf(8583952875138065417l));
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcase.setExternalId("ExternalId2040460158");
        java.util.List<com.thed.service.soap.RemoteDefect> _createNewTestcase_remoteRepositoryTreeTestcaseTestcaseDefects = new java.util.ArrayList<com.thed.service.soap.RemoteDefect>();
        com.thed.service.soap.RemoteDefect _createNewTestcase_remoteRepositoryTreeTestcaseTestcaseDefectsVal1 = new com.thed.service.soap.RemoteDefect();
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcaseDefectsVal1.setDefectId(Long.valueOf(-6142104372425726866l));
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcaseDefectsVal1.setDescription("Description1411308420");
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcaseDefectsVal1.setCreatedDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.156+05:30"));
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcaseDefectsVal1.setDefectStatus("DefectStatus960315975");
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcaseDefectsVal1.setPriority("Priority-848582160");
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcaseDefectsVal1.setSeverity("Severity1268039891");
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcaseDefects.add(_createNewTestcase_remoteRepositoryTreeTestcaseTestcaseDefectsVal1);
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcase.getDefects().addAll(_createNewTestcase_remoteRepositoryTreeTestcaseTestcaseDefects);
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcase.setAutomated(Boolean.valueOf(false));
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcase.setScriptId("ScriptId-1866820232");
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcase.setScriptName("ScriptName39434967");
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcase.setScriptPath("ScriptPath-203888419");
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcase.setReleaseId(Long.valueOf(5429583041485839877l));
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcase.setOldId(Long.valueOf(-4011382957572420695l));
        java.util.List<java.lang.Long> _createNewTestcase_remoteRepositoryTreeTestcaseTestcaseRequirements = new java.util.ArrayList<java.lang.Long>();
        java.lang.Long _createNewTestcase_remoteRepositoryTreeTestcaseTestcaseRequirementsVal1 = Long.valueOf(1989666190728349165l);
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcaseRequirements.add(_createNewTestcase_remoteRepositoryTreeTestcaseTestcaseRequirementsVal1);
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcase.getRequirements().addAll(_createNewTestcase_remoteRepositoryTreeTestcaseTestcaseRequirements);
        _createNewTestcase_remoteRepositoryTreeTestcaseTestcase.setAttachmentCount(Integer.valueOf(-745384867));
        _createNewTestcase_remoteRepositoryTreeTestcase.setTestcase(_createNewTestcase_remoteRepositoryTreeTestcaseTestcase);
        _createNewTestcase_remoteRepositoryTreeTestcase.setOriginal(true);
        _createNewTestcase_remoteRepositoryTreeTestcase.setTestSteps("TestSteps-821958788");
        java.lang.String _createNewTestcase_token = "_createNewTestcase_token1631465358";
        try {
            java.util.List<com.thed.service.soap.RemoteFieldValue> _createNewTestcase__return = port.createNewTestcase(_createNewTestcase_remoteRepositoryTreeTestcase, _createNewTestcase_token);
            System.out.println("createNewTestcase.result=" + _createNewTestcase__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getRequirementById...");
        java.lang.Long _getRequirementById_requirementId = Long.valueOf(6968369729046529505l);
        java.lang.String _getRequirementById_token = "_getRequirementById_token1491506808";
        try {
            com.thed.service.soap.RemoteRequirement _getRequirementById__return = port.getRequirementById(_getRequirementById_requirementId, _getRequirementById_token);
            System.out.println("getRequirementById.result=" + _getRequirementById__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTestSchedulesById...");
        java.lang.Long _getTestSchedulesById_testScheduleId = Long.valueOf(-2032576757865531289l);
        java.lang.String _getTestSchedulesById_token = "_getTestSchedulesById_token1842359053";
        try {
            com.thed.service.soap.RemoteReleaseTestSchedule _getTestSchedulesById__return = port.getTestSchedulesById(_getTestSchedulesById_testScheduleId, _getTestSchedulesById_token);
            System.out.println("getTestSchedulesById.result=" + _getTestSchedulesById__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createNewCycle...");
        com.thed.service.soap.RemoteCycle _createNewCycle_remoteCycle = new com.thed.service.soap.RemoteCycle();
        _createNewCycle_remoteCycle.setId(Long.valueOf(5193388121524839412l));
        _createNewCycle_remoteCycle.setName("Name-1727290363");
        _createNewCycle_remoteCycle.setBuild("Build390203171");
        _createNewCycle_remoteCycle.setEnvironment("Environment-729533787");
        _createNewCycle_remoteCycle.setStartDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.165+05:30"));
        _createNewCycle_remoteCycle.setEndDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.168+05:30"));
        _createNewCycle_remoteCycle.setStatus(Integer.valueOf(91656376));
        _createNewCycle_remoteCycle.setReleaseId(Long.valueOf(517486993509663423l));
        java.util.List<com.thed.service.soap.RemotePhase> _createNewCycle_remoteCycleRemotePhases = new java.util.ArrayList<com.thed.service.soap.RemotePhase>();
        com.thed.service.soap.RemotePhase _createNewCycle_remoteCycleRemotePhasesVal1 = new com.thed.service.soap.RemotePhase();
        _createNewCycle_remoteCycleRemotePhasesVal1.setId(Long.valueOf(3530297298779315866l));
        com.thed.service.soap.RemoteNameValue _createNewCycle_remoteCycleRemotePhasesVal1RemoteRepository = new com.thed.service.soap.RemoteNameValue();
        com.thed.service.soap.RemoteData _createNewCycle_remoteCycleRemotePhasesVal1RemoteRepositoryRemoteData = new com.thed.service.soap.RemoteData();
        _createNewCycle_remoteCycleRemotePhasesVal1RemoteRepositoryRemoteData.setId(-4589214599128565875l);
        _createNewCycle_remoteCycleRemotePhasesVal1RemoteRepositoryRemoteData.setName("Name282007379");
        _createNewCycle_remoteCycleRemotePhasesVal1RemoteRepository.setRemoteData(_createNewCycle_remoteCycleRemotePhasesVal1RemoteRepositoryRemoteData);
        _createNewCycle_remoteCycleRemotePhasesVal1.setRemoteRepository(_createNewCycle_remoteCycleRemotePhasesVal1RemoteRepository);
        _createNewCycle_remoteCycleRemotePhasesVal1.setStartDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.171+05:30"));
        _createNewCycle_remoteCycleRemotePhasesVal1.setEndDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.174+05:30"));
        _createNewCycle_remoteCycleRemotePhasesVal1.setFreeForm(Boolean.valueOf(false));
        com.thed.service.soap.RemoteNameValue _createNewCycle_remoteCycleRemotePhasesVal1RemoteCycle = new com.thed.service.soap.RemoteNameValue();
        com.thed.service.soap.RemoteData _createNewCycle_remoteCycleRemotePhasesVal1RemoteCycleRemoteData = new com.thed.service.soap.RemoteData();
        _createNewCycle_remoteCycleRemotePhasesVal1RemoteCycleRemoteData.setId(-7081236489088833030l);
        _createNewCycle_remoteCycleRemotePhasesVal1RemoteCycleRemoteData.setName("Name2026527082");
        _createNewCycle_remoteCycleRemotePhasesVal1RemoteCycle.setRemoteData(_createNewCycle_remoteCycleRemotePhasesVal1RemoteCycleRemoteData);
        _createNewCycle_remoteCycleRemotePhasesVal1.setRemoteCycle(_createNewCycle_remoteCycleRemotePhasesVal1RemoteCycle);
        _createNewCycle_remoteCycleRemotePhases.add(_createNewCycle_remoteCycleRemotePhasesVal1);
        _createNewCycle_remoteCycle.getRemotePhases().addAll(_createNewCycle_remoteCycleRemotePhases);
        java.lang.String _createNewCycle_token = "_createNewCycle_token-256430152";
        try {
            java.lang.Long _createNewCycle__return = port.createNewCycle(_createNewCycle_remoteCycle, _createNewCycle_token);
            System.out.println("createNewCycle.result=" + _createNewCycle__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createNewRequirementTree...");
        com.thed.service.soap.RemoteRequirementTree _createNewRequirementTree_remoteRequirementTree = new com.thed.service.soap.RemoteRequirementTree();
        _createNewRequirementTree_remoteRequirementTree.setId(Long.valueOf(7511183541973199406l));
        _createNewRequirementTree_remoteRequirementTree.setName("Name-690941354");
        _createNewRequirementTree_remoteRequirementTree.setDescription("Description-1197067652");
        _createNewRequirementTree_remoteRequirementTree.setProjectId(Long.valueOf(2410878704413757496l));
        com.thed.service.soap.RemoteRequirementTree _createNewRequirementTree_remoteRequirementTreeParent = new com.thed.service.soap.RemoteRequirementTree();
        _createNewRequirementTree_remoteRequirementTreeParent.setId(Long.valueOf(8634849784049244888l));
        _createNewRequirementTree_remoteRequirementTreeParent.setName("Name-1526785992");
        _createNewRequirementTree_remoteRequirementTreeParent.setDescription("Description36046731");
        _createNewRequirementTree_remoteRequirementTreeParent.setProjectId(Long.valueOf(-6400446414982373772l));
        com.thed.service.soap.RemoteRequirementTree _createNewRequirementTree_remoteRequirementTreeParentParent = new com.thed.service.soap.RemoteRequirementTree();
        _createNewRequirementTree_remoteRequirementTreeParentParent.setId(Long.valueOf(4453560180528897448l));
        _createNewRequirementTree_remoteRequirementTreeParentParent.setName("Name-1918744465");
        _createNewRequirementTree_remoteRequirementTreeParentParent.setDescription("Description-1215861412");
        _createNewRequirementTree_remoteRequirementTreeParentParent.setProjectId(Long.valueOf(101182388660307996l));
        com.thed.service.soap.RemoteRequirementTree _createNewRequirementTree_remoteRequirementTreeParentParentParent = new com.thed.service.soap.RemoteRequirementTree();
        _createNewRequirementTree_remoteRequirementTreeParentParentParent.setId(Long.valueOf(-5685109400135898346l));
        _createNewRequirementTree_remoteRequirementTreeParentParentParent.setName("Name1807457447");
        _createNewRequirementTree_remoteRequirementTreeParentParentParent.setDescription("Description-1147923027");
        _createNewRequirementTree_remoteRequirementTreeParentParentParent.setProjectId(Long.valueOf(5284073738065339638l));
                _createNewRequirementTree_remoteRequirementTreeParentParentParent.setParent(null);
        java.util.List<com.thed.service.soap.RemoteData> _createNewRequirementTree_remoteRequirementTreeParentParentParentCategories = new java.util.ArrayList<com.thed.service.soap.RemoteData>();
        _createNewRequirementTree_remoteRequirementTreeParentParentParent.getCategories().addAll(_createNewRequirementTree_remoteRequirementTreeParentParentParentCategories);
        _createNewRequirementTree_remoteRequirementTreeParentParentParent.setCreatedOn(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.180+05:30"));
        _createNewRequirementTree_remoteRequirementTreeParentParentParent.setCreatedBy(Long.valueOf(513936746951868112l));
        _createNewRequirementTree_remoteRequirementTreeParentParentParent.setLastModifiedBy(Long.valueOf(7581003491432356271l));
        _createNewRequirementTree_remoteRequirementTreeParentParentParent.setLastModifiedOn(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.180+05:30"));
        java.util.List<java.lang.Long> _createNewRequirementTree_remoteRequirementTreeParentParentParentReleaseIds = new java.util.ArrayList<java.lang.Long>();
        _createNewRequirementTree_remoteRequirementTreeParentParentParent.getReleaseIds().addAll(_createNewRequirementTree_remoteRequirementTreeParentParentParentReleaseIds);
        _createNewRequirementTree_remoteRequirementTreeParentParentParent.setType("Type482074368");
        _createNewRequirementTree_remoteRequirementTreeParentParent.setParent(_createNewRequirementTree_remoteRequirementTreeParentParentParent);
        java.util.List<com.thed.service.soap.RemoteData> _createNewRequirementTree_remoteRequirementTreeParentParentCategories = new java.util.ArrayList<com.thed.service.soap.RemoteData>();
        _createNewRequirementTree_remoteRequirementTreeParentParent.getCategories().addAll(_createNewRequirementTree_remoteRequirementTreeParentParentCategories);
        _createNewRequirementTree_remoteRequirementTreeParentParent.setCreatedOn(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.183+05:30"));
        _createNewRequirementTree_remoteRequirementTreeParentParent.setCreatedBy(Long.valueOf(-543588254529221012l));
        _createNewRequirementTree_remoteRequirementTreeParentParent.setLastModifiedBy(Long.valueOf(-7368832178239032978l));
        _createNewRequirementTree_remoteRequirementTreeParentParent.setLastModifiedOn(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.186+05:30"));
        java.util.List<java.lang.Long> _createNewRequirementTree_remoteRequirementTreeParentParentReleaseIds = new java.util.ArrayList<java.lang.Long>();
        _createNewRequirementTree_remoteRequirementTreeParentParent.getReleaseIds().addAll(_createNewRequirementTree_remoteRequirementTreeParentParentReleaseIds);
        _createNewRequirementTree_remoteRequirementTreeParentParent.setType("Type-1735478395");
        _createNewRequirementTree_remoteRequirementTreeParent.setParent(_createNewRequirementTree_remoteRequirementTreeParentParent);
        java.util.List<com.thed.service.soap.RemoteData> _createNewRequirementTree_remoteRequirementTreeParentCategories = new java.util.ArrayList<com.thed.service.soap.RemoteData>();
        com.thed.service.soap.RemoteData _createNewRequirementTree_remoteRequirementTreeParentCategoriesVal1 = new com.thed.service.soap.RemoteData();
        _createNewRequirementTree_remoteRequirementTreeParentCategoriesVal1.setId(-8060299346824221790l);
        _createNewRequirementTree_remoteRequirementTreeParentCategoriesVal1.setName("Name645467329");
        _createNewRequirementTree_remoteRequirementTreeParentCategories.add(_createNewRequirementTree_remoteRequirementTreeParentCategoriesVal1);
        _createNewRequirementTree_remoteRequirementTreeParent.getCategories().addAll(_createNewRequirementTree_remoteRequirementTreeParentCategories);
        _createNewRequirementTree_remoteRequirementTreeParent.setCreatedOn(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.186+05:30"));
        _createNewRequirementTree_remoteRequirementTreeParent.setCreatedBy(Long.valueOf(3306655889429906691l));
        _createNewRequirementTree_remoteRequirementTreeParent.setLastModifiedBy(Long.valueOf(-9070035385174139611l));
        _createNewRequirementTree_remoteRequirementTreeParent.setLastModifiedOn(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.186+05:30"));
        java.util.List<java.lang.Long> _createNewRequirementTree_remoteRequirementTreeParentReleaseIds = new java.util.ArrayList<java.lang.Long>();
        java.lang.Long _createNewRequirementTree_remoteRequirementTreeParentReleaseIdsVal1 = Long.valueOf(-345777093686575175l);
        _createNewRequirementTree_remoteRequirementTreeParentReleaseIds.add(_createNewRequirementTree_remoteRequirementTreeParentReleaseIdsVal1);
        _createNewRequirementTree_remoteRequirementTreeParent.getReleaseIds().addAll(_createNewRequirementTree_remoteRequirementTreeParentReleaseIds);
        _createNewRequirementTree_remoteRequirementTreeParent.setType("Type-984051484");
        _createNewRequirementTree_remoteRequirementTree.setParent(_createNewRequirementTree_remoteRequirementTreeParent);
        java.util.List<com.thed.service.soap.RemoteData> _createNewRequirementTree_remoteRequirementTreeCategories = new java.util.ArrayList<com.thed.service.soap.RemoteData>();
        com.thed.service.soap.RemoteData _createNewRequirementTree_remoteRequirementTreeCategoriesVal1 = new com.thed.service.soap.RemoteData();
        _createNewRequirementTree_remoteRequirementTreeCategoriesVal1.setId(-2585418864172151907l);
        _createNewRequirementTree_remoteRequirementTreeCategoriesVal1.setName("Name1044555777");
        _createNewRequirementTree_remoteRequirementTreeCategories.add(_createNewRequirementTree_remoteRequirementTreeCategoriesVal1);
        _createNewRequirementTree_remoteRequirementTree.getCategories().addAll(_createNewRequirementTree_remoteRequirementTreeCategories);
        _createNewRequirementTree_remoteRequirementTree.setCreatedOn(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.189+05:30"));
        _createNewRequirementTree_remoteRequirementTree.setCreatedBy(Long.valueOf(5382664366645651308l));
        _createNewRequirementTree_remoteRequirementTree.setLastModifiedBy(Long.valueOf(3653560848974511104l));
        _createNewRequirementTree_remoteRequirementTree.setLastModifiedOn(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.189+05:30"));
        java.util.List<java.lang.Long> _createNewRequirementTree_remoteRequirementTreeReleaseIds = new java.util.ArrayList<java.lang.Long>();
        java.lang.Long _createNewRequirementTree_remoteRequirementTreeReleaseIdsVal1 = Long.valueOf(-9083507014957188783l);
        _createNewRequirementTree_remoteRequirementTreeReleaseIds.add(_createNewRequirementTree_remoteRequirementTreeReleaseIdsVal1);
        _createNewRequirementTree_remoteRequirementTree.getReleaseIds().addAll(_createNewRequirementTree_remoteRequirementTreeReleaseIds);
        _createNewRequirementTree_remoteRequirementTree.setType("Type1368221534");
        java.lang.String _createNewRequirementTree_token = "_createNewRequirementTree_token-1096475212";
        try {
            java.lang.Long _createNewRequirementTree__return = port.createNewRequirementTree(_createNewRequirementTree_remoteRequirementTree, _createNewRequirementTree_token);
            System.out.println("createNewRequirementTree.result=" + _createNewRequirementTree__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getUserById...");
        java.lang.Long _getUserById_userId = Long.valueOf(-3561133714024066161l);
        java.lang.String _getUserById_token = "_getUserById_token-186967229";
        try {
            com.thed.service.soap.RemoteUser _getUserById__return = port.getUserById(_getUserById_userId, _getUserById_token);
            System.out.println("getUserById.result=" + _getUserById__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createNewRequirement...");
        com.thed.service.soap.RemoteRequirement _createNewRequirement_remoteRequirement = new com.thed.service.soap.RemoteRequirement();
        com.thed.service.soap.RemoteCustomizableEntity.CustomProperties _createNewRequirement_remoteRequirementCustomProperties = new com.thed.service.soap.RemoteCustomizableEntity.CustomProperties();
        java.util.List<com.thed.service.soap.RemoteCustomizableEntity.CustomProperties.Entry> _createNewRequirement_remoteRequirementCustomPropertiesEntry = new java.util.ArrayList<com.thed.service.soap.RemoteCustomizableEntity.CustomProperties.Entry>();
        com.thed.service.soap.RemoteCustomizableEntity.CustomProperties.Entry _createNewRequirement_remoteRequirementCustomPropertiesEntryVal1 = new com.thed.service.soap.RemoteCustomizableEntity.CustomProperties.Entry();
        java.lang.Object _createNewRequirement_remoteRequirementCustomPropertiesEntryVal1Key = null;
        _createNewRequirement_remoteRequirementCustomPropertiesEntryVal1.setKey(_createNewRequirement_remoteRequirementCustomPropertiesEntryVal1Key);
        java.lang.Object _createNewRequirement_remoteRequirementCustomPropertiesEntryVal1Value = null;
        _createNewRequirement_remoteRequirementCustomPropertiesEntryVal1.setValue(_createNewRequirement_remoteRequirementCustomPropertiesEntryVal1Value);
        _createNewRequirement_remoteRequirementCustomPropertiesEntry.add(_createNewRequirement_remoteRequirementCustomPropertiesEntryVal1);
        _createNewRequirement_remoteRequirementCustomProperties.getEntry().addAll(_createNewRequirement_remoteRequirementCustomPropertiesEntry);
        _createNewRequirement_remoteRequirement.setCustomProperties(_createNewRequirement_remoteRequirementCustomProperties);
        _createNewRequirement_remoteRequirement.setId(Long.valueOf(-2180430129468979953l));
        java.util.List<java.lang.Long> _createNewRequirement_remoteRequirementRequirementId = new java.util.ArrayList<java.lang.Long>();
        java.lang.Long _createNewRequirement_remoteRequirementRequirementIdVal1 = Long.valueOf(-1867986871707292115l);
        _createNewRequirement_remoteRequirementRequirementId.add(_createNewRequirement_remoteRequirementRequirementIdVal1);
        _createNewRequirement_remoteRequirement.getRequirementId().addAll(_createNewRequirement_remoteRequirementRequirementId);
        _createNewRequirement_remoteRequirement.setRequirementTreeId(Long.valueOf(3796952363192131789l));
        _createNewRequirement_remoteRequirement.setName("Name-361605347");
        _createNewRequirement_remoteRequirement.setPriority("Priority287545687");
        _createNewRequirement_remoteRequirement.setUrl("Url-239401542");
        _createNewRequirement_remoteRequirement.setDetails("Details-1561567416");
        _createNewRequirement_remoteRequirement.setExternalId("ExternalId1950022190");
        java.util.List<java.lang.Long> _createNewRequirement_remoteRequirementReleaseIds = new java.util.ArrayList<java.lang.Long>();
        java.lang.Long _createNewRequirement_remoteRequirementReleaseIdsVal1 = Long.valueOf(7775564969139001640l);
        _createNewRequirement_remoteRequirementReleaseIds.add(_createNewRequirement_remoteRequirementReleaseIdsVal1);
        _createNewRequirement_remoteRequirement.getReleaseIds().addAll(_createNewRequirement_remoteRequirementReleaseIds);
        _createNewRequirement_remoteRequirement.setCreatedBy(Long.valueOf(5826615617441881704l));
        _createNewRequirement_remoteRequirement.setLastModifiedBy(Long.valueOf(6581402397441036152l));
        _createNewRequirement_remoteRequirement.setCreatedOn(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.198+05:30"));
        _createNewRequirement_remoteRequirement.setLastModifiedOn(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.201+05:30"));
        java.util.List<java.lang.Long> _createNewRequirement_remoteRequirementTestcaseIds = new java.util.ArrayList<java.lang.Long>();
        java.lang.Long _createNewRequirement_remoteRequirementTestcaseIdsVal1 = Long.valueOf(-7002059009453918528l);
        _createNewRequirement_remoteRequirementTestcaseIds.add(_createNewRequirement_remoteRequirementTestcaseIdsVal1);
        _createNewRequirement_remoteRequirement.getTestcaseIds().addAll(_createNewRequirement_remoteRequirementTestcaseIds);
        _createNewRequirement_remoteRequirement.setAttachmentCount(Integer.valueOf(1457337875));
        _createNewRequirement_remoteRequirement.setRequirementType(Integer.valueOf(2106026936));
        java.lang.String _createNewRequirement_token = "_createNewRequirement_token22534005";
        try {
            java.lang.Long _createNewRequirement__return = port.createNewRequirement(_createNewRequirement_remoteRequirement, _createNewRequirement_token);
            System.out.println("createNewRequirement.result=" + _createNewRequirement__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getReleasesByCriteria...");
        java.util.List<com.thed.service.soap.RemoteCriteria> _getReleasesByCriteria_searchCriterias = new java.util.ArrayList<com.thed.service.soap.RemoteCriteria>();
        com.thed.service.soap.RemoteCriteria _getReleasesByCriteria_searchCriteriasVal1 = new com.thed.service.soap.RemoteCriteria();
        _getReleasesByCriteria_searchCriteriasVal1.setSearchName("SearchName23552264");
        com.thed.service.soap.SearchOperation _getReleasesByCriteria_searchCriteriasVal1SearchOperation = com.thed.service.soap.SearchOperation.BETWEEN;
        _getReleasesByCriteria_searchCriteriasVal1.setSearchOperation(_getReleasesByCriteria_searchCriteriasVal1SearchOperation);
        _getReleasesByCriteria_searchCriteriasVal1.setSearchValue("SearchValue-701767728");
        _getReleasesByCriteria_searchCriterias.add(_getReleasesByCriteria_searchCriteriasVal1);
        java.lang.Boolean _getReleasesByCriteria_returnAllDataFlag = Boolean.valueOf(true);
        java.lang.String _getReleasesByCriteria_token = "_getReleasesByCriteria_token1166987124";
        try {
            java.util.List<com.thed.service.soap.RemoteRelease> _getReleasesByCriteria__return = port.getReleasesByCriteria(_getReleasesByCriteria_searchCriterias, _getReleasesByCriteria_returnAllDataFlag, _getReleasesByCriteria_token);
            System.out.println("getReleasesByCriteria.result=" + _getReleasesByCriteria__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getRequirementTreeById...");
        java.lang.Long _getRequirementTreeById_requirementTreeid = Long.valueOf(-612078353461576802l);
        java.lang.String _getRequirementTreeById_token = "_getRequirementTreeById_token280259941";
        try {
            com.thed.service.soap.RemoteRequirementTree _getRequirementTreeById__return = port.getRequirementTreeById(_getRequirementTreeById_requirementTreeid, _getRequirementTreeById_token);
            System.out.println("getRequirementTreeById.result=" + _getRequirementTreeById__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getCyclesByCriteria...");
        java.util.List<com.thed.service.soap.RemoteCriteria> _getCyclesByCriteria_searchCriterias = new java.util.ArrayList<com.thed.service.soap.RemoteCriteria>();
        com.thed.service.soap.RemoteCriteria _getCyclesByCriteria_searchCriteriasVal1 = new com.thed.service.soap.RemoteCriteria();
        _getCyclesByCriteria_searchCriteriasVal1.setSearchName("SearchName-1419016616");
        com.thed.service.soap.SearchOperation _getCyclesByCriteria_searchCriteriasVal1SearchOperation = com.thed.service.soap.SearchOperation.LIKE;
        _getCyclesByCriteria_searchCriteriasVal1.setSearchOperation(_getCyclesByCriteria_searchCriteriasVal1SearchOperation);
        _getCyclesByCriteria_searchCriteriasVal1.setSearchValue("SearchValue416492130");
        _getCyclesByCriteria_searchCriterias.add(_getCyclesByCriteria_searchCriteriasVal1);
        java.lang.Boolean _getCyclesByCriteria_returnAllDataFlag = Boolean.valueOf(true);
        java.lang.String _getCyclesByCriteria_token = "_getCyclesByCriteria_token-1834225098";
        try {
            java.util.List<com.thed.service.soap.RemoteCycle> _getCyclesByCriteria__return = port.getCyclesByCriteria(_getCyclesByCriteria_searchCriterias, _getCyclesByCriteria_returnAllDataFlag, _getCyclesByCriteria_token);
            System.out.println("getCyclesByCriteria.result=" + _getCyclesByCriteria__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking logout...");
        java.lang.String _logout_token = "_logout_token-1139838060";
        try {
            port.logout(_logout_token);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTestcasesByCriteria...");
        java.util.List<com.thed.service.soap.RemoteCriteria> _getTestcasesByCriteria_searchCriterias = new java.util.ArrayList<com.thed.service.soap.RemoteCriteria>();
        com.thed.service.soap.RemoteCriteria _getTestcasesByCriteria_searchCriteriasVal1 = new com.thed.service.soap.RemoteCriteria();
        _getTestcasesByCriteria_searchCriteriasVal1.setSearchName("SearchName-1338514852");
        com.thed.service.soap.SearchOperation _getTestcasesByCriteria_searchCriteriasVal1SearchOperation = com.thed.service.soap.SearchOperation.IS_NULL;
        _getTestcasesByCriteria_searchCriteriasVal1.setSearchOperation(_getTestcasesByCriteria_searchCriteriasVal1SearchOperation);
        _getTestcasesByCriteria_searchCriteriasVal1.setSearchValue("SearchValue1826167288");
        _getTestcasesByCriteria_searchCriterias.add(_getTestcasesByCriteria_searchCriteriasVal1);
        java.lang.Boolean _getTestcasesByCriteria_returnAllDataFlag = Boolean.valueOf(true);
        java.lang.String _getTestcasesByCriteria_token = "_getTestcasesByCriteria_token887630515";
        try {
            java.util.List<com.thed.service.soap.RemoteRepositoryTreeTestcase> _getTestcasesByCriteria__return = port.getTestcasesByCriteria(_getTestcasesByCriteria_searchCriterias, _getTestcasesByCriteria_returnAllDataFlag, _getTestcasesByCriteria_token);
            System.out.println("getTestcasesByCriteria.result=" + _getTestcasesByCriteria__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking addAttachments...");
        java.util.List<com.thed.service.soap.RemoteAttachment> _addAttachments_remoteAttachments = new java.util.ArrayList<com.thed.service.soap.RemoteAttachment>();
        com.thed.service.soap.RemoteAttachment _addAttachments_remoteAttachmentsVal1 = new com.thed.service.soap.RemoteAttachment();
        _addAttachments_remoteAttachmentsVal1.setId(Long.valueOf(-2745067858686283399l));
        _addAttachments_remoteAttachmentsVal1.setRefId("RefId1458252743");
        _addAttachments_remoteAttachmentsVal1.setFileSize(Long.valueOf(1828914003755478720l));
        _addAttachments_remoteAttachmentsVal1.setMimeType("MimeType223334473");
        _addAttachments_remoteAttachmentsVal1.setEntityId(Long.valueOf(-8953343716540302165l));
        _addAttachments_remoteAttachmentsVal1.setEntityName("EntityName145396729");
        _addAttachments_remoteAttachmentsVal1.setFileName("FileName1274843313");
        _addAttachments_remoteAttachmentsVal1.setAuthor("Author676794931");
        _addAttachments_remoteAttachmentsVal1.setDescription("Description802940317");
        byte[] _addAttachments_remoteAttachmentsVal1Attachment = new byte[] {};
        _addAttachments_remoteAttachmentsVal1.setAttachment(_addAttachments_remoteAttachmentsVal1Attachment);
        _addAttachments_remoteAttachmentsVal1.setCreationDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.210+05:30"));
        _addAttachments_remoteAttachmentsVal1.setAttachmentURI("AttachmentURI406511352");
        _addAttachments_remoteAttachments.add(_addAttachments_remoteAttachmentsVal1);
        java.lang.String _addAttachments_token = "_addAttachments_token480451316";
        try {
            java.util.List<com.thed.service.soap.RemoteFieldValue> _addAttachments__return = port.addAttachments(_addAttachments_remoteAttachments, _addAttachments_token);
            System.out.println("addAttachments.result=" + _addAttachments__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteAttachmentById...");
        java.lang.Long _deleteAttachmentById_attachmentId = Long.valueOf(-7572296380767795946l);
        java.lang.String _deleteAttachmentById_token = "_deleteAttachmentById_token-619596782";
        try {
            com.thed.service.soap.RemoteFieldValue _deleteAttachmentById__return = port.deleteAttachmentById(_deleteAttachmentById_attachmentId, _deleteAttachmentById_token);
            System.out.println("deleteAttachmentById.result=" + _deleteAttachmentById__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getUsersByCriteria...");
        java.util.List<com.thed.service.soap.RemoteCriteria> _getUsersByCriteria_searchCriterias = new java.util.ArrayList<com.thed.service.soap.RemoteCriteria>();
        com.thed.service.soap.RemoteCriteria _getUsersByCriteria_searchCriteriasVal1 = new com.thed.service.soap.RemoteCriteria();
        _getUsersByCriteria_searchCriteriasVal1.setSearchName("SearchName1333158104");
        com.thed.service.soap.SearchOperation _getUsersByCriteria_searchCriteriasVal1SearchOperation = com.thed.service.soap.SearchOperation.LESS_THAN;
        _getUsersByCriteria_searchCriteriasVal1.setSearchOperation(_getUsersByCriteria_searchCriteriasVal1SearchOperation);
        _getUsersByCriteria_searchCriteriasVal1.setSearchValue("SearchValue-134450728");
        _getUsersByCriteria_searchCriterias.add(_getUsersByCriteria_searchCriteriasVal1);
        java.lang.Boolean _getUsersByCriteria_returnAllDataFlag = Boolean.valueOf(false);
        java.lang.String _getUsersByCriteria_token = "_getUsersByCriteria_token-1296888476";
        try {
            java.util.List<com.thed.service.soap.RemoteUser> _getUsersByCriteria__return = port.getUsersByCriteria(_getUsersByCriteria_searchCriterias, _getUsersByCriteria_returnAllDataFlag, _getUsersByCriteria_token);
            System.out.println("getUsersByCriteria.result=" + _getUsersByCriteria__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getProjectById...");
        java.lang.Long _getProjectById_projectId = Long.valueOf(2100694328692648483l);
        java.lang.String _getProjectById_token = "_getProjectById_token-1707610401";
        try {
            com.thed.service.soap.RemoteProject _getProjectById__return = port.getProjectById(_getProjectById_projectId, _getProjectById_token);
            System.out.println("getProjectById.result=" + _getProjectById__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getReleaseById...");
        java.lang.Long _getReleaseById_releaseId = Long.valueOf(-2272509208583788360l);
        java.lang.String _getReleaseById_token = "_getReleaseById_token1154295131";
        try {
            com.thed.service.soap.RemoteRelease _getReleaseById__return = port.getReleaseById(_getReleaseById_releaseId, _getReleaseById_token);
            System.out.println("getReleaseById.result=" + _getReleaseById__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAttachmentById...");
        java.lang.Long _getAttachmentById_attachmentId = Long.valueOf(-1031953044615638713l);
        java.lang.String _getAttachmentById_token = "_getAttachmentById_token875398411";
        try {
            com.thed.service.soap.RemoteAttachment _getAttachmentById__return = port.getAttachmentById(_getAttachmentById_attachmentId, _getAttachmentById_token);
            System.out.println("getAttachmentById.result=" + _getAttachmentById__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getCycleById...");
        java.lang.Long _getCycleById_cycleId = Long.valueOf(5651063051590799793l);
        java.lang.String _getCycleById_token = "_getCycleById_token-820611480";
        try {
            com.thed.service.soap.RemoteCycle _getCycleById__return = port.getCycleById(_getCycleById_cycleId, _getCycleById_token);
            System.out.println("getCycleById.result=" + _getCycleById__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateAttachment...");
        com.thed.service.soap.RemoteAttachment _updateAttachment_remoteAttachment = new com.thed.service.soap.RemoteAttachment();
        _updateAttachment_remoteAttachment.setId(Long.valueOf(6529471863944997213l));
        _updateAttachment_remoteAttachment.setRefId("RefId1660761964");
        _updateAttachment_remoteAttachment.setFileSize(Long.valueOf(4722071561670553696l));
        _updateAttachment_remoteAttachment.setMimeType("MimeType-1519981349");
        _updateAttachment_remoteAttachment.setEntityId(Long.valueOf(-5015208516283973159l));
        _updateAttachment_remoteAttachment.setEntityName("EntityName197789990");
        _updateAttachment_remoteAttachment.setFileName("FileName321194935");
        _updateAttachment_remoteAttachment.setAuthor("Author-565962584");
        _updateAttachment_remoteAttachment.setDescription("Description407473784");
        byte[] _updateAttachment_remoteAttachmentAttachment = new byte[] {};
        _updateAttachment_remoteAttachment.setAttachment(_updateAttachment_remoteAttachmentAttachment);
        _updateAttachment_remoteAttachment.setCreationDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2015-05-01T14:59:10.222+05:30"));
        _updateAttachment_remoteAttachment.setAttachmentURI("AttachmentURI1352284180");
        java.lang.String _updateAttachment_token = "_updateAttachment_token1507342938";
        try {
            com.thed.service.soap.RemoteFieldValue _updateAttachment__return = port.updateAttachment(_updateAttachment_remoteAttachment, _updateAttachment_token);
            System.out.println("updateAttachment.result=" + _updateAttachment__return);

        } catch (ZephyrServiceException e) { 
            System.out.println("Expected exception: ZephyrServiceException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

	private static void createTest(ZephyrSoapService port, String token) throws ZephyrServiceException {
	
		RemoteCriteria remoteCriteria = new RemoteCriteria();
		RemoteCriteria remoteCriteria2 = new RemoteCriteria();
		RemoteRepositoryTree tree = new RemoteRepositoryTree();
		List<RemoteRepositoryTree> treeList = new ArrayList<RemoteRepositoryTree>();
		List<RemoteCriteria> rcList = new ArrayList<RemoteCriteria>();
		RemoteRepositoryTreeTestcase treeTestcase = new RemoteRepositoryTreeTestcase();
		RemoteTestcase testcase = new RemoteTestcase();


		// Search criteria to look for all repository trees//phases in release 2
		remoteCriteria.setSearchName("releaseId");
		remoteCriteria.setSearchOperation(SearchOperation.EQUALS);
		remoteCriteria.setSearchValue("1");
		// Search criteria to additionally look for all trees//phases named
		// DevZone (in the above release 2)
		remoteCriteria2.setSearchName("name");
		remoteCriteria2.setSearchOperation(SearchOperation.EQUALS);
		remoteCriteria2.setSearchValue("phase4");
		// Adding the search criteria to the Remote Criteria list
		rcList.add(remoteCriteria);
		rcList.add(remoteCriteria2);
		//
		treeList = port.getTestCaseTreesByCriteria(rcList, false, token);
		// I know only 1 folder will be found so I use that one in this sample

		// If none are found or more than one tree is returned, you will need to
		// write code to handle that
		tree = treeList.get(0);
		// Enter field information for the testcase
		testcase.setName("This Testcase was created via API");
		testcase.setComments("Created via API!");
		testcase.setAutomated(false);
		testcase.setExternalId("99999");
		testcase.setPriority("1");
		testcase.setTag("API");
		// Set release the testcase will be located at
		testcase.setReleaseId(tree.getReleaseId());
		// Repository trees//phases Id used to link the new testcase to a
		// tree//phase
		treeTestcase.setRemoteRepositoryId(tree.getId());
		// Adding test steps to the testcase
		treeTestcase
				.setTestSteps("<steps maxId=\"3\"><step id=\"1\" orderId=\"1\" detail=\"Test Step 1\" data=\"Test Data \" result=\"Excepted Results \" />"
						+ "<step id=\"2\" orderId=\"2\" detail=\"Test Step T2\" data=\"\" result=\"\" />"
						+ "<step id=\"3\" orderId=\"3\" detail=\"Test Step T3 - Test\" data=\"\" result=\"\" /></steps>");
		// Loading the testcase object I changed just above into the
		// remoteRepositoryTreeTestcase object
		treeTestcase.setTestcase(testcase);

		// Actually creating the new TC here
		// With bulk testcases you may want to use loops and list arrays
		// Response from Zephyr will give a list of 2 values; (0)-TCR Tree
		// Testcase ID, (1)-Testcase ID (The one you see in the UI)
		List<RemoteFieldValue> response = port.createNewTestcase(
				treeTestcase, token);
		System.out.println("\n" + "Testcase Created!");
		System.out.println(response.get(0).getKey() + ": "
				+ response.get(0).getValue());
		System.out.println(response.get(1).getKey() + ": "
				+ response.get(1).getValue());
		
		
	}

}
