package com.thed.service.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-05-01T14:59:10.842+05:30
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "ZephyrSoapService", 
                  wsdlLocation = "http://192.168.152.130/flex/services/soap/zephyrsoapservice-v1?wsdl",
                  targetNamespace = "http://soap.service.thed.com/") 
public class ZephyrSoapService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.service.thed.com/", "ZephyrSoapService");
    public final static QName ZephyrSoapServiceImplPort = new QName("http://soap.service.thed.com/", "ZephyrSoapServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.152.130/flex/services/soap/zephyrsoapservice-v1?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZephyrSoapService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.152.130/flex/services/soap/zephyrsoapservice-v1?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZephyrSoapService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZephyrSoapService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZephyrSoapService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZephyrSoapService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZephyrSoapService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ZephyrSoapService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns ZephyrSoapService
     */
    @WebEndpoint(name = "ZephyrSoapServiceImplPort")
    public ZephyrSoapService getZephyrSoapServiceImplPort() {
        return super.getPort(ZephyrSoapServiceImplPort, ZephyrSoapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZephyrSoapService
     */
    @WebEndpoint(name = "ZephyrSoapServiceImplPort")
    public ZephyrSoapService getZephyrSoapServiceImplPort(WebServiceFeature... features) {
        return super.getPort(ZephyrSoapServiceImplPort, ZephyrSoapService.class, features);
    }

}
