package com.thed.service.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-05-01T14:59:10.765+05:30
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://soap.service.thed.com/", name = "ZephyrSoapService")
@XmlSeeAlso({ObjectFactory.class})
public interface ZephyrSoapService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTestcaseTreeById", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetTestcaseTreeById")
    @WebMethod
    @ResponseWrapper(localName = "getTestcaseTreeByIdResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetTestcaseTreeByIdResponse")
    public com.thed.service.soap.RemoteRepositoryTree getTestcaseTreeById(
        @WebParam(name = "remoteRepositoryId", targetNamespace = "")
        java.lang.Long remoteRepositoryId,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateTestStatus", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.UpdateTestStatus")
    @WebMethod
    @ResponseWrapper(localName = "updateTestStatusResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.UpdateTestStatusResponse")
    public java.util.List<com.thed.service.soap.RemoteFieldValue> updateTestStatus(
        @WebParam(name = "testResults", targetNamespace = "")
        java.util.List<com.thed.service.soap.RemoteTestResult> testResults,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateRequirement", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.UpdateRequirement")
    @WebMethod
    @ResponseWrapper(localName = "updateRequirementResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.UpdateRequirementResponse")
    public java.lang.Long updateRequirement(
        @WebParam(name = "remoteRequirementId", targetNamespace = "")
        java.lang.Long remoteRequirementId,
        @WebParam(name = "remoteFieldValues", targetNamespace = "")
        java.util.List<com.thed.service.soap.RemoteFieldValue> remoteFieldValues,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTestCaseTreesByCriteria", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetTestCaseTreesByCriteria")
    @WebMethod
    @ResponseWrapper(localName = "getTestCaseTreesByCriteriaResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetTestCaseTreesByCriteriaResponse")
    public java.util.List<com.thed.service.soap.RemoteRepositoryTree> getTestCaseTreesByCriteria(
        @WebParam(name = "searchCriterias", targetNamespace = "")
        java.util.List<com.thed.service.soap.RemoteCriteria> searchCriterias,
        @WebParam(name = "returnAllDataFlag", targetNamespace = "")
        java.lang.Boolean returnAllDataFlag,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRequirementsByCriteria", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetRequirementsByCriteria")
    @WebMethod
    @ResponseWrapper(localName = "getRequirementsByCriteriaResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetRequirementsByCriteriaResponse")
    public java.util.List<com.thed.service.soap.RemoteRequirement> getRequirementsByCriteria(
        @WebParam(name = "searchCriterias", targetNamespace = "")
        java.util.List<com.thed.service.soap.RemoteCriteria> searchCriterias,
        @WebParam(name = "returnAllDataFlag", targetNamespace = "")
        java.lang.Boolean returnAllDataFlag,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getProjectsByCriteria", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetProjectsByCriteria")
    @WebMethod
    @ResponseWrapper(localName = "getProjectsByCriteriaResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetProjectsByCriteriaResponse")
    public java.util.List<com.thed.service.soap.RemoteProject> getProjectsByCriteria(
        @WebParam(name = "searchCriterias", targetNamespace = "")
        java.util.List<com.thed.service.soap.RemoteCriteria> searchCriterias,
        @WebParam(name = "returnAllDataFlag", targetNamespace = "")
        java.lang.Boolean returnAllDataFlag,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCustomFields", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetCustomFields")
    @WebMethod
    @ResponseWrapper(localName = "getCustomFieldsResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetCustomFieldsResponse")
    public java.util.List<com.thed.service.soap.RemoteCustomField> getCustomFields(
        @WebParam(name = "entityName", targetNamespace = "")
        java.lang.String entityName,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRequirementTreesByCriteria", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetRequirementTreesByCriteria")
    @WebMethod
    @ResponseWrapper(localName = "getRequirementTreesByCriteriaResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetRequirementTreesByCriteriaResponse")
    public java.util.List<com.thed.service.soap.RemoteRequirementTree> getRequirementTreesByCriteria(
        @WebParam(name = "searchCriterias", targetNamespace = "")
        java.util.List<com.thed.service.soap.RemoteCriteria> searchCriterias,
        @WebParam(name = "returnAllDataFlag", targetNamespace = "")
        java.lang.Boolean returnAllDataFlag,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addPhaseToCycle", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.AddPhaseToCycle")
    @WebMethod
    @ResponseWrapper(localName = "addPhaseToCycleResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.AddPhaseToCycleResponse")
    public java.lang.Long addPhaseToCycle(
        @WebParam(name = "remotePhase", targetNamespace = "")
        com.thed.service.soap.RemotePhase remotePhase,
        @WebParam(name = "bulkAssign", targetNamespace = "")
        java.lang.Integer bulkAssign,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAttachmentsByCriteria", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetAttachmentsByCriteria")
    @WebMethod
    @ResponseWrapper(localName = "getAttachmentsByCriteriaResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetAttachmentsByCriteriaResponse")
    public java.util.List<com.thed.service.soap.RemoteAttachment> getAttachmentsByCriteria(
        @WebParam(name = "searchCriterias", targetNamespace = "")
        java.util.List<com.thed.service.soap.RemoteCriteria> searchCriterias,
        @WebParam(name = "returnAllDataFlag", targetNamespace = "")
        java.lang.Boolean returnAllDataFlag,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "assignTestSchedules", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.AssignTestSchedules")
    @WebMethod
    @ResponseWrapper(localName = "assignTestSchedulesResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.AssignTestSchedulesResponse")
    public java.util.List<com.thed.service.soap.RemoteFieldValue> assignTestSchedules(
        @WebParam(name = "remoteReleaseTestSchedules", targetNamespace = "")
        java.util.List<com.thed.service.soap.RemoteReleaseTestSchedule> remoteReleaseTestSchedules,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createNewTestcaseTree", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.CreateNewTestcaseTree")
    @WebMethod
    @ResponseWrapper(localName = "createNewTestcaseTreeResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.CreateNewTestcaseTreeResponse")
    public java.lang.Long createNewTestcaseTree(
        @WebParam(name = "remoteRepositoryTree", targetNamespace = "")
        com.thed.service.soap.RemoteRepositoryTree remoteRepositoryTree,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTestcaseById", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetTestcaseById")
    @WebMethod
    @ResponseWrapper(localName = "getTestcaseByIdResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetTestcaseByIdResponse")
    public com.thed.service.soap.RemoteRepositoryTreeTestcase getTestcaseById(
        @WebParam(name = "testcaseId", targetNamespace = "")
        java.lang.Long testcaseId,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteAttachmentsByCriteria", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.DeleteAttachmentsByCriteria")
    @WebMethod
    @ResponseWrapper(localName = "deleteAttachmentsByCriteriaResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.DeleteAttachmentsByCriteriaResponse")
    public java.util.List<com.thed.service.soap.RemoteFieldValue> deleteAttachmentsByCriteria(
        @WebParam(name = "entityName", targetNamespace = "")
        java.lang.String entityName,
        @WebParam(name = "entityId", targetNamespace = "")
        java.lang.Long entityId,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateTestcase", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.UpdateTestcase")
    @WebMethod
    @ResponseWrapper(localName = "updateTestcaseResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.UpdateTestcaseResponse")
    public java.lang.Long updateTestcase(
        @WebParam(name = "testCaseId", targetNamespace = "")
        java.lang.Long testCaseId,
        @WebParam(name = "remoteFieldValues", targetNamespace = "")
        java.util.List<com.thed.service.soap.RemoteFieldValue> remoteFieldValues,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTestSchedulesByCriteria", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetTestSchedulesByCriteria")
    @WebMethod
    @ResponseWrapper(localName = "getTestSchedulesByCriteriaResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetTestSchedulesByCriteriaResponse")
    public java.util.List<com.thed.service.soap.RemoteReleaseTestSchedule> getTestSchedulesByCriteria(
        @WebParam(name = "searchCriterias", targetNamespace = "")
        java.util.List<com.thed.service.soap.RemoteCriteria> searchCriterias,
        @WebParam(name = "returnAllDataFlag", targetNamespace = "")
        java.lang.Boolean returnAllDataFlag,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.Login")
    @WebMethod
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.LoginResponse")
    public java.lang.String login(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createNewTestcase", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.CreateNewTestcase")
    @WebMethod
    @ResponseWrapper(localName = "createNewTestcaseResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.CreateNewTestcaseResponse")
    public java.util.List<com.thed.service.soap.RemoteFieldValue> createNewTestcase(
        @WebParam(name = "remoteRepositoryTreeTestcase", targetNamespace = "")
        com.thed.service.soap.RemoteRepositoryTreeTestcase remoteRepositoryTreeTestcase,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRequirementById", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetRequirementById")
    @WebMethod
    @ResponseWrapper(localName = "getRequirementByIdResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetRequirementByIdResponse")
    public com.thed.service.soap.RemoteRequirement getRequirementById(
        @WebParam(name = "requirementId", targetNamespace = "")
        java.lang.Long requirementId,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTestSchedulesById", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetTestSchedulesById")
    @WebMethod
    @ResponseWrapper(localName = "getTestSchedulesByIdResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetTestSchedulesByIdResponse")
    public com.thed.service.soap.RemoteReleaseTestSchedule getTestSchedulesById(
        @WebParam(name = "testScheduleId", targetNamespace = "")
        java.lang.Long testScheduleId,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createNewCycle", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.CreateNewCycle")
    @WebMethod
    @ResponseWrapper(localName = "createNewCycleResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.CreateNewCycleResponse")
    public java.lang.Long createNewCycle(
        @WebParam(name = "remoteCycle", targetNamespace = "")
        com.thed.service.soap.RemoteCycle remoteCycle,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createNewRequirementTree", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.CreateNewRequirementTree")
    @WebMethod
    @ResponseWrapper(localName = "createNewRequirementTreeResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.CreateNewRequirementTreeResponse")
    public java.lang.Long createNewRequirementTree(
        @WebParam(name = "remoteRequirementTree", targetNamespace = "")
        com.thed.service.soap.RemoteRequirementTree remoteRequirementTree,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserById", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetUserById")
    @WebMethod
    @ResponseWrapper(localName = "getUserByIdResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetUserByIdResponse")
    public com.thed.service.soap.RemoteUser getUserById(
        @WebParam(name = "userId", targetNamespace = "")
        java.lang.Long userId,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createNewRequirement", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.CreateNewRequirement")
    @WebMethod
    @ResponseWrapper(localName = "createNewRequirementResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.CreateNewRequirementResponse")
    public java.lang.Long createNewRequirement(
        @WebParam(name = "remoteRequirement", targetNamespace = "")
        com.thed.service.soap.RemoteRequirement remoteRequirement,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getReleasesByCriteria", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetReleasesByCriteria")
    @WebMethod
    @ResponseWrapper(localName = "getReleasesByCriteriaResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetReleasesByCriteriaResponse")
    public java.util.List<com.thed.service.soap.RemoteRelease> getReleasesByCriteria(
        @WebParam(name = "searchCriterias", targetNamespace = "")
        java.util.List<com.thed.service.soap.RemoteCriteria> searchCriterias,
        @WebParam(name = "returnAllDataFlag", targetNamespace = "")
        java.lang.Boolean returnAllDataFlag,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRequirementTreeById", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetRequirementTreeById")
    @WebMethod
    @ResponseWrapper(localName = "getRequirementTreeByIdResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetRequirementTreeByIdResponse")
    public com.thed.service.soap.RemoteRequirementTree getRequirementTreeById(
        @WebParam(name = "requirementTreeid", targetNamespace = "")
        java.lang.Long requirementTreeid,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCyclesByCriteria", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetCyclesByCriteria")
    @WebMethod
    @ResponseWrapper(localName = "getCyclesByCriteriaResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetCyclesByCriteriaResponse")
    public java.util.List<com.thed.service.soap.RemoteCycle> getCyclesByCriteria(
        @WebParam(name = "searchCriterias", targetNamespace = "")
        java.util.List<com.thed.service.soap.RemoteCriteria> searchCriterias,
        @WebParam(name = "returnAllDataFlag", targetNamespace = "")
        java.lang.Boolean returnAllDataFlag,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @RequestWrapper(localName = "logout", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.Logout")
    @WebMethod
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.LogoutResponse")
    public void logout(
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTestcasesByCriteria", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetTestcasesByCriteria")
    @WebMethod
    @ResponseWrapper(localName = "getTestcasesByCriteriaResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetTestcasesByCriteriaResponse")
    public java.util.List<com.thed.service.soap.RemoteRepositoryTreeTestcase> getTestcasesByCriteria(
        @WebParam(name = "searchCriterias", targetNamespace = "")
        java.util.List<com.thed.service.soap.RemoteCriteria> searchCriterias,
        @WebParam(name = "returnAllDataFlag", targetNamespace = "")
        java.lang.Boolean returnAllDataFlag,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addAttachments", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.AddAttachments")
    @WebMethod
    @ResponseWrapper(localName = "addAttachmentsResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.AddAttachmentsResponse")
    public java.util.List<com.thed.service.soap.RemoteFieldValue> addAttachments(
        @WebParam(name = "remoteAttachments", targetNamespace = "")
        java.util.List<com.thed.service.soap.RemoteAttachment> remoteAttachments,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteAttachmentById", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.DeleteAttachmentById")
    @WebMethod
    @ResponseWrapper(localName = "deleteAttachmentByIdResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.DeleteAttachmentByIdResponse")
    public com.thed.service.soap.RemoteFieldValue deleteAttachmentById(
        @WebParam(name = "attachmentId", targetNamespace = "")
        java.lang.Long attachmentId,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUsersByCriteria", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetUsersByCriteria")
    @WebMethod
    @ResponseWrapper(localName = "getUsersByCriteriaResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetUsersByCriteriaResponse")
    public java.util.List<com.thed.service.soap.RemoteUser> getUsersByCriteria(
        @WebParam(name = "searchCriterias", targetNamespace = "")
        java.util.List<com.thed.service.soap.RemoteCriteria> searchCriterias,
        @WebParam(name = "returnAllDataFlag", targetNamespace = "")
        java.lang.Boolean returnAllDataFlag,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getProjectById", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetProjectById")
    @WebMethod
    @ResponseWrapper(localName = "getProjectByIdResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetProjectByIdResponse")
    public com.thed.service.soap.RemoteProject getProjectById(
        @WebParam(name = "projectId", targetNamespace = "")
        java.lang.Long projectId,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getReleaseById", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetReleaseById")
    @WebMethod
    @ResponseWrapper(localName = "getReleaseByIdResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetReleaseByIdResponse")
    public com.thed.service.soap.RemoteRelease getReleaseById(
        @WebParam(name = "releaseId", targetNamespace = "")
        java.lang.Long releaseId,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAttachmentById", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetAttachmentById")
    @WebMethod
    @ResponseWrapper(localName = "getAttachmentByIdResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetAttachmentByIdResponse")
    public com.thed.service.soap.RemoteAttachment getAttachmentById(
        @WebParam(name = "attachmentId", targetNamespace = "")
        java.lang.Long attachmentId,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCycleById", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetCycleById")
    @WebMethod
    @ResponseWrapper(localName = "getCycleByIdResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.GetCycleByIdResponse")
    public com.thed.service.soap.RemoteCycle getCycleById(
        @WebParam(name = "cycleId", targetNamespace = "")
        java.lang.Long cycleId,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateAttachment", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.UpdateAttachment")
    @WebMethod
    @ResponseWrapper(localName = "updateAttachmentResponse", targetNamespace = "http://soap.service.thed.com/", className = "com.thed.service.soap.UpdateAttachmentResponse")
    public com.thed.service.soap.RemoteFieldValue updateAttachment(
        @WebParam(name = "remoteAttachment", targetNamespace = "")
        com.thed.service.soap.RemoteAttachment remoteAttachment,
        @WebParam(name = "token", targetNamespace = "")
        java.lang.String token
    ) throws ZephyrServiceException;
}
